install:
  - dotnet restore

configuration:
  - Release

after_build:
    - nuget pack PocketContainer\PocketContainer.nuspec  
    - nuget pack PocketContainer\PocketContainerOpenGenericStrategy.nuspec  
    - nuget pack PocketContainer\PocketContainerPrimitiveAvoidanceStrategy.nuspec  
    - nuget pack PocketContainer\PocketContainer.Clone.nuspec  
    - nuget pack PocketContainer\PocketContainerSingleImplementationStrategy.nuspec  
    - nuget pack PocketContainer\TypeDiscovery.nuspec  

build:
  project: PocketContainer.sln

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
    - path: '*.nupkg'