install:
  - nuget restore

configuration:
  - Release

build:
  project: PocketContainer.sln

after_build:
	- nuget pack PocketContainer.nuspec -p "Configuration=Release;Platform=AnyCPU" 

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
	*.nupkg