install:
  - nuget restore

configuration:
  - Release

after_build:
	- nuget pack PocketContainer.nuspec -p "Configuration=Release;Platform=AnyCPU" 

build:
  project: PocketContainer.sln

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
	- path: *.nupkg