configuration:
  - Release

build_script:
  - cmd: >-
      dotnet build PocketContainer.sln /p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - nuget pack Pocket.Container\PocketContainer.nuspec  
  - nuget pack Pocket.Container\PocketContainerOpenGenericStrategy.nuspec  
  - nuget pack Pocket.Container\PocketContainerPrimitiveAvoidanceStrategy.nuspec  
  - nuget pack Pocket.Container\PocketContainer.Clone.nuspec  
  - nuget pack Pocket.Container\PocketContainerSingleImplementationStrategy.nuspec  
  - nuget pack Pocket.Container\TypeDiscovery.nuspec  

test_script:
  - cmd: dotnet test .\Pocket.Container.Tests\Pocket.Container.Tests.csproj -l:trx

artifacts:
    - path: '**\*.nupkg'