install:
  - dotnet restore

configuration:
  - Release

after_build:
    - nuget pack Pocket.Container\PocketContainer.nuspec  
    - nuget pack Pocket.Container\PocketContainerOpenGenericStrategy.nuspec  
    - nuget pack Pocket.Container\PocketContainerPrimitiveAvoidanceStrategy.nuspec  
    - nuget pack Pocket.Container\PocketContainer.Clone.nuspec  
    - nuget pack Pocket.Container\PocketContainerSingleImplementationStrategy.nuspec  
    - nuget pack Pocket.Container\TypeDiscovery.nuspec  

build:
  project: PocketContainer.sln

test_script:
  - cmd: dotnet test .\Pocket.Container.Tests\Pocket.Container.Tests.csproj -l:trx

artifacts:
    - path: '*.nupkg'